### ISSUE TITLE
Load .yml resources from several folders

### ISSUE THREAD

**Issue by miloshavlicek** [Kdyby/Translation#69]
I would need to automatically load .yml file resources from several folders, but I do not know if it is possible. I have tried to specify more directories in config.neon, but resources are loaded only from a first directory.

**Comment by fprochazka** [comment]
You should be able to [configure multiple directories](https://github.com/Kdyby/Translation/blob/6a1d0ce6a50b96e877bbc0a37bb5e754a106c2e0/src/Kdyby/Translation/DI/TranslationExtension.php#L49), but they're [filtered and checked for existence](https://github.com/Kdyby/Translation/blob/6a1d0ce6a50b96e877bbc0a37bb5e754a106c2e0/src/Kdyby/Translation/DI/TranslationExtension.php#L313).

Also, the container is not rebuild, if you add new files, because it's not scanning the directories. It's rebuild only when you change already loaded files.

**Comment by miloshavlicek** [comment]
Yeah, thanks! The problem was probably caused because container wasn't rebuilt.
I apologize for the interruption. Thank you!

**Comment by fprochazka** [comment]
No worries! I plan to solve this, it's just a low priority :)
